### ISSUE TITLE
Idea to simplify the extraction and management of scripture corpora

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#133]
We can run experiments with just the New Testament or just the Old Testament data and with all the data by extracting data from the project with different settings:
`python -m silnlp.common.extract_corpora project `
`python -m silnlp.common.extract_corpora project --include NT`
`python -m silnlp.common.extract_corpora project --include OT`

This will create three separate files in the scripture folder.

Would there be an advantage to having only the option to extract all the data once, and instead specify the slice of the data to be used in the config.yml file. 

```
  corpus_pairs:
  - type: train,test,val
    include_scripture: NT 
    src:  abp-ABP
    trg: en-ABPBTE
    val_size: 250
    test_size: 250
```
Options for the use: would be combinations of "OT" "NT" "DC" and the default would be "ALL"

Pros:
Easier to run the extraction as there are fewer options.
Reduce the duplication of data in the scripture folder.
Easier to keep track of the filename used by a project as it wouldn't vary.

Cons: 
The work needed to implement the change
More complicated config.yml file

**Comment by ddaspit** [comment]
This is currently possible using the `corpus_books` config option. There is also a similar option to specify which books to include in the test set (`test_books`).
```
  corpus_pairs:
  - type: train,test,val
    corpus_books: NT 
    src:  abp-ABP
    trg: en-ABPBTE
    val_size: 250
    test_size: 250
```
