### ISSUE TITLE
When using multiple corpus pairs, key terms are pulled multiple times.

### ISSUE THREAD

**Issue by bhartmoore** [sillsdev/silnlp#333]
When using multiple corpus pairs, the same project key terms are included in the training set multiple times, once following the verses for each pair. We should only get them once. (You can also see this happening in the logging output from preprocess.py.)

Attached files are from S:\MT\experiments\FT-Benin\NLLB.1.3B.dist.en_BSB+en_CSB-ddn_DDN2_Terms:
[train.src.txt](https://github.com/sillsdev/silnlp/files/14408111/train.src.txt)
[train.trg.txt](https://github.com/sillsdev/silnlp/files/14408112/train.trg.txt)

Here's a look at how the corpus pairs and terms are set up in the config:
```
data:
  corpus_pairs:
  - corpus_books: GEN,RUT,MAT,LUK,JUD
    src: en-CSB
    test_size: 150
    trg: ddn-DDN2_2024_02_14
    type: train,test,val
    val_size: 100
  - corpus_books: PHP,COL,1TH,2TH,1TI,2TI,TIT,PHM,JAS,1PE,2PE
    src: en-BSB
    trg: ddn-DDN2_2024_02_14
    type: train
  lang_codes:
    ddn: ddn_Latn
    en: eng_Latn
  seed: 111
  terms:
    dictionary: false
    include_glosses: true
    train: true
```
