### ISSUE TITLE
Project KBT's paired with incorrect glosses during preprocessing

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#659]
A project (aArp) uses a project-specific key Biblical terms list:
`  <BiblicalTermsListSetting>Project:aArp:ProjectBiblicalTerms.xml</BiblicalTermsListSetting>`
The project is paired with an English translation for NMT model training, with key Biblical terms included in the training setup, as shown below:
```
  corpus_pairs:
  - src: en-NIV11R
    trg: aps-aArp_2025_02_14
    type: train
  lang_codes:
    en: eng_Latn
    aps: aps_Latn
  seed: 111
  terms:
    dictionary: false
    include_glosses: true
    train: true
```
After preprocessing, the source (English) and target (Arop) glosses are not being paired correctly as shown in the examples below.
**train.src.detok.txt (English terms)**
```
Jeroham
Lord
Jeroham
give thanks
humankind
Adummim
...
```
**train.src.detok.txt (Arop terms)**
```
Roda
niy prum iyn takwa watana re soldia iyn Israel
ailan Rodes
Alfius
Galesia
Galili
...
```

It appears that the English major glosses are getting paired with the project-specific Arop glosses.  Since the list of terms in the Major KBT list differs from the list of project-specific KBT's, this pairing is not correct.
